#!/bin/bash
# Proposal presets (makroskop-48o): the new catalog shocks, then one joint --package solve per proposal
# (etl/proposal_specs.json, generated by `bun run proposals:specs`). Shock runs go to etl/shock_gdx_48o/
# (NOT scanned by extract.py) until verified; joint solves go to etl/proposal_gdx/.
#   setsid nohup bash cloud/run_proposals.sh > proposals.log 2>&1 < /dev/null &
# Sequential (one factorization at a time), idempotent, resumable from checkpoints.
# Idempotent means an existing output is SKIPped, never re-solved: after a sizing or figure change
# (new meta.json sizing, an edited proposal, a new proposal_specs.json) delete the stale
# proposal_gdx/Forslag_<id>.gdx first — otherwise the old joint solve stays, and proposals_check.py
# refuses it as stale.
set -uo pipefail
cd "$(dirname "$0")/../etl"
export PATH="$HOME/.local/bin:$PATH"
export PYTHONUNBUFFERED=1
echo 1000 > /proc/self/oom_score_adj 2>/dev/null || true
mkdir -p shock_gdx_48o proposal_gdx

run() {
  local out="$1"; shift
  if [ -f "$out" ]; then echo "SKIP $out (already exported)"; return; fi
  echo "=============================================================="
  echo "SCENARIO $out  $(date -Is)"
  echo "=============================================================="
  uv run python freesolver.py solve-export --from-year 2030 --shock-years 2030-2129 "$@" --out "$out" \
    || echo "FAILED: $out (continuing with the rest)"
}

run shock_gdx_48o/Topskat_ufin.gdx --shock-name tTop --shock-delta 0.01
run shock_gdx_48o/Topskat_perm.gdx --shock-name tTop --shock-delta 0.01 --closure tax-reaction
run shock_gdx_48o/Beskaeftigelsesfradrag_ufin.gdx --shock-name tBeskFradrag --shock-delta 0.01
run shock_gdx_48o/Beskaeftigelsesfradrag_perm.gdx --shock-name tBeskFradrag --shock-delta 0.01 --closure tax-reaction

while IFS=$'\t' read -r id pkg; do
  run "proposal_gdx/Forslag_${id}.gdx" --package "$pkg" < /dev/null
done < <(uv run python -c "import json; [print(f'{k}\t{v[\"package\"]}') for k, v in json.load(open('proposal_specs.json')).items()]")
echo "=== $(date -Is) PROPOSAL RUNS DONE ==="
